#ifndef CONFIG_H
#define CONFIG_H

// LCD pins
#define LCD_PWR 7
#define LCD_RST 0
#define LCD_CS 5
#define LCD_DC 42
#define LCD_SCK 10
#define LCD_MOSI 11
#define LCD_MISO 12

// TSC2046 touch pins
#define TOUCH_CLK 14
#define TOUCH_CS 20
#define TOUCH_MISO 1
#define TOUCH_MOSI 2
#define TOUCH_IRQ 35

// GPBA02B extend IO pins
#define EXTEND_SPI_CS 47
#define EXTEND_SPI_MISO 46
#define EXTEND_SPI_MOSI 45
#define EXTEND_SPI_CLK 48

#define GPIO_PIN_MASK(pin) (1ULL << (pin))

#define LCD_PIN_MASK (GPIO_PIN_MASK(LCD_PWR) | GPIO_PIN_MASK(LCD_RST) | GPIO_PIN_MASK(LCD_CS) | GPIO_PIN_MASK(LCD_DC) | GPIO_PIN_MASK(LCD_SCK) | GPIO_PIN_MASK(LCD_MOSI) | GPIO_PIN_MASK(LCD_MISO))
#define TOUCH_PIN_MASK (GPIO_PIN_MASK(TOUCH_CLK) | GPIO_PIN_MASK(TOUCH_CS) | GPIO_PIN_MASK(TOUCH_MISO) | GPIO_PIN_MASK(TOUCH_MOSI) | GPIO_PIN_MASK(TOUCH_IRQ))
#define EXTEND_PIN_MASK (GPIO_PIN_MASK(EXTEND_SPI_CS) | GPIO_PIN_MASK(EXTEND_SPI_MISO) | GPIO_PIN_MASK(EXTEND_SPI_MOSI) | GPIO_PIN_MASK(EXTEND_SPI_CLK))

_Static_assert((LCD_PIN_MASK & TOUCH_PIN_MASK) == 0, "LCD and TSC2046 GPIO pins conflict");
_Static_assert((LCD_PIN_MASK & EXTEND_PIN_MASK) == 0, "LCD and GPBA02B GPIO pins conflict");
_Static_assert((TOUCH_PIN_MASK & EXTEND_PIN_MASK) == 0, "TSC2046 and GPBA02B GPIO pins conflict");

#endif