#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#if defined(__has_include)
#if __has_include("esp_lcd_panel_nv3041.h")
#include "esp_lcd_panel_nv3041.h"
#define HAVE_NV3041_PANEL 1
#else
#include "esp_lcd_panel_st7789.h"
#define HAVE_NV3041_PANEL 0
#endif
#else
#include "esp_lcd_panel_st7789.h"
#define HAVE_NV3041_PANEL 0
#endif

#ifndef JOHN_AI_USE_USER_UI
#define JOHN_AI_USE_USER_UI 1
#endif

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_46
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_48
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_47

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_NC
#define TOUCH_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// Shared reset pin for peripherals (IO0)
#define PERIPHERAL_RESET_GPIO GPIO_NUM_0
#define PERIPHERAL_RESET_ACTIVE_LOW 1
#define PERIPHERAL_RESET_PULSE_MS 10

#define PERIPHERAL_I2C_SDA_PIN GPIO_NUM_17
#define PERIPHERAL_I2C_SCL_PIN GPIO_NUM_18

// LCD (NV3041A) on SPI2
#define DISPLAY_CS_PIN GPIO_NUM_5
#define DISPLAY_DC_PIN GPIO_NUM_42
#define DISPLAY_CLK_PIN GPIO_NUM_10
#define DISPLAY_MOSI_PIN GPIO_NUM_11
#define DISPLAY_MISO_PIN GPIO_NUM_12
#define DISPLAY_RST_PIN PERIPHERAL_RESET_GPIO

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 272
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR false
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_SPI_MODE 0

// Touch (TSC2046) on SPI3
#define TOUCH_CLK_PIN GPIO_NUM_14
#define TOUCH_CS_PIN GPIO_NUM_20
#define TOUCH_MISO_PIN GPIO_NUM_1
#define TOUCH_MOSI_PIN GPIO_NUM_2
#define TOUCH_IRQ_PIN GPIO_NUM_35

#endif  // _BOARD_CONFIG_H_
